# Be sure to restart your server when you modify this file.

# defaults across all environments
defaults: &defaults
  database_url: "<%= ENV.fetch("DATABASE_URL") %>"
  secret_key_base: "<%= ENV.fetch("SECRET_KEY_BASE") %>"
  slack_active: "<%= ENV.fetch("SLACK_ACTIVE") %>"
  slack_webhook_url: "<%= ENV.fetch("SLACK_WEBHOOK_URL") %>"

# apply shared configuration to environments
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
